spring.datasource.data: classpath:sql/import.sql
spring.datasource.schema: classpath:sql/schema.sql

spring.datasource.initialization-mode: always
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
kube.datasource.default: "127.0.0.1:3306/kubeworksdb"
spring.datasource.url: "jdbc:mysql://${MYSQL_DB_PATH:${kube.datasource.default}}?characterEncoding=utf8&autoReconnect=true&connectTimeout=5500&socketTimeout=5500&retriesAllDown=3"
spring.datasource.username: ${MYSQL_DB_USERNAME:root}
spring.datasource.password: ${MYSQL_DB_PASSWORD:root}

spring.jpa.database: mysql
spring.jpa.hibernate.ddl-auto: none
spring.jpa.properties.hibernate.hbm2ddl.import_files: ""

spring.h2.console.enabled: false
